# Generated by Django 2.2 on 2019-06-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='players',
        ),
    ]
