# Generated by Django 2.2 on 2019-06-19 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190617_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country1', to='service.Country')),
                ('country2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country2', to='service.Country')),
                ('players', models.ManyToManyField(to='service.Player')),
            ],
        ),
    ]
